### ISSUE TITLE
[feat] [doc] Create Website for BiocTools/BiocSuite

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/biocswirl-dev-team.github.io#1]
# [feat] [doc] Create Website for BiocTools/BiocSuite

# Tasks 
- [ ] Import "terminal"-like style sheet
- [x] Design/create theme (that falls under an open license (w/ commercial modification) and conveys the feel of our package) 

# Add pages for: (including installation instructions, about, uses)
- [x] Main Page + Index (mainly pulls from README) 
- [ ] BiocSwirl 
- [ ] BiocTerm
- [ ] BioVim 
- [ ] Add Prospective Contributors Page 
- [ ] Add About the Project (including Hackseq, original dev team, the story, etc)

# Resources

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)

**Comment by lisancao** [comment]
This repo is no longer going to be used for the website. See bioinformaticstutorials.github.io instead.
